// Generated by gencpp from file pimouse_ros/TimedMotion.msg
// DO NOT EDIT!


#ifndef PIMOUSE_ROS_MESSAGE_TIMEDMOTION_H
#define PIMOUSE_ROS_MESSAGE_TIMEDMOTION_H

#include <ros/service_traits.h>


#include <pimouse_ros/TimedMotionRequest.h>
#include <pimouse_ros/TimedMotionResponse.h>


namespace pimouse_ros
{

struct TimedMotion
{

typedef TimedMotionRequest Request;
typedef TimedMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TimedMotion
} // namespace pimouse_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pimouse_ros::TimedMotion > {
  static const char* value()
  {
    return "d80c56ffd8662963140a2b3157f57615";
  }

  static const char* value(const ::pimouse_ros::TimedMotion&) { return value(); }
};

template<>
struct DataType< ::pimouse_ros::TimedMotion > {
  static const char* value()
  {
    return "pimouse_ros/TimedMotion";
  }

  static const char* value(const ::pimouse_ros::TimedMotion&) { return value(); }
};


// service_traits::MD5Sum< ::pimouse_ros::TimedMotionRequest> should match 
// service_traits::MD5Sum< ::pimouse_ros::TimedMotion > 
template<>
struct MD5Sum< ::pimouse_ros::TimedMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pimouse_ros::TimedMotion >::value();
  }
  static const char* value(const ::pimouse_ros::TimedMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pimouse_ros::TimedMotionRequest> should match 
// service_traits::DataType< ::pimouse_ros::TimedMotion > 
template<>
struct DataType< ::pimouse_ros::TimedMotionRequest>
{
  static const char* value()
  {
    return DataType< ::pimouse_ros::TimedMotion >::value();
  }
  static const char* value(const ::pimouse_ros::TimedMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pimouse_ros::TimedMotionResponse> should match 
// service_traits::MD5Sum< ::pimouse_ros::TimedMotion > 
template<>
struct MD5Sum< ::pimouse_ros::TimedMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pimouse_ros::TimedMotion >::value();
  }
  static const char* value(const ::pimouse_ros::TimedMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pimouse_ros::TimedMotionResponse> should match 
// service_traits::DataType< ::pimouse_ros::TimedMotion > 
template<>
struct DataType< ::pimouse_ros::TimedMotionResponse>
{
  static const char* value()
  {
    return DataType< ::pimouse_ros::TimedMotion >::value();
  }
  static const char* value(const ::pimouse_ros::TimedMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIMOUSE_ROS_MESSAGE_TIMEDMOTION_H
