(cl:defpackage raspimouse_ros_2-msg
  (:use )
  (:export
   "<BUTTONVALUES>"
   "BUTTONVALUES"
   "<LEDVALUES>"
   "LEDVALUES"
   "<LIGHTSENSORVALUES>"
   "LIGHTSENSORVALUES"
   "<MOTORFREQS>"
   "MOTORFREQS"
   "<MUSICACTION>"
   "MUSICACTION"
   "<MUSICACTIONFEEDBACK>"
   "MUSICACTIONFEEDBACK"
   "<MUSICACTIONGOAL>"
   "MUSICACTIONGOAL"
   "<MUSICACTIONRESULT>"
   "MUSICACTIONRESULT"
   "<MUSICFEEDBACK>"
   "MUSICFEEDBACK"
   "<MUSICGOAL>"
   "MUSICGOAL"
   "<MUSICRESULT>"
   "MUSICRESULT"
  ))

