// Generated by gencpp from file raspimouse_ros_2/TimedMotion.msg
// DO NOT EDIT!


#ifndef RASPIMOUSE_ROS_2_MESSAGE_TIMEDMOTION_H
#define RASPIMOUSE_ROS_2_MESSAGE_TIMEDMOTION_H

#include <ros/service_traits.h>


#include <raspimouse_ros_2/TimedMotionRequest.h>
#include <raspimouse_ros_2/TimedMotionResponse.h>


namespace raspimouse_ros_2
{

struct TimedMotion
{

typedef TimedMotionRequest Request;
typedef TimedMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TimedMotion
} // namespace raspimouse_ros_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::raspimouse_ros_2::TimedMotion > {
  static const char* value()
  {
    return "d80c56ffd8662963140a2b3157f57615";
  }

  static const char* value(const ::raspimouse_ros_2::TimedMotion&) { return value(); }
};

template<>
struct DataType< ::raspimouse_ros_2::TimedMotion > {
  static const char* value()
  {
    return "raspimouse_ros_2/TimedMotion";
  }

  static const char* value(const ::raspimouse_ros_2::TimedMotion&) { return value(); }
};


// service_traits::MD5Sum< ::raspimouse_ros_2::TimedMotionRequest> should match 
// service_traits::MD5Sum< ::raspimouse_ros_2::TimedMotion > 
template<>
struct MD5Sum< ::raspimouse_ros_2::TimedMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::raspimouse_ros_2::TimedMotion >::value();
  }
  static const char* value(const ::raspimouse_ros_2::TimedMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::raspimouse_ros_2::TimedMotionRequest> should match 
// service_traits::DataType< ::raspimouse_ros_2::TimedMotion > 
template<>
struct DataType< ::raspimouse_ros_2::TimedMotionRequest>
{
  static const char* value()
  {
    return DataType< ::raspimouse_ros_2::TimedMotion >::value();
  }
  static const char* value(const ::raspimouse_ros_2::TimedMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::raspimouse_ros_2::TimedMotionResponse> should match 
// service_traits::MD5Sum< ::raspimouse_ros_2::TimedMotion > 
template<>
struct MD5Sum< ::raspimouse_ros_2::TimedMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::raspimouse_ros_2::TimedMotion >::value();
  }
  static const char* value(const ::raspimouse_ros_2::TimedMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::raspimouse_ros_2::TimedMotionResponse> should match 
// service_traits::DataType< ::raspimouse_ros_2::TimedMotion > 
template<>
struct DataType< ::raspimouse_ros_2::TimedMotionResponse>
{
  static const char* value()
  {
    return DataType< ::raspimouse_ros_2::TimedMotion >::value();
  }
  static const char* value(const ::raspimouse_ros_2::TimedMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RASPIMOUSE_ROS_2_MESSAGE_TIMEDMOTION_H
